package(default_visibility = ["//tools/cpp:__pkg__"])

filegroup(
    name = "gcc",
    srcs = [
        "aarch64_glibc_stable_2022-08-1_gcc",
        "@aarch64_glibc_stable_2022-08-1//:gcc",
    ],
)

filegroup(
    name = "ar",
    srcs = [
        "aarch64_glibc_stable_2022-08-1_ar",
        "@aarch64_glibc_stable_2022-08-1//:ar",
    ],
)

filegroup(
    name = "as",
    srcs = [
        "aarch64_glibc_stable_2022-08-1_as",
        "@aarch64_glibc_stable_2022-08-1//:as",
    ],
)

filegroup(
    name = "ld",
    srcs = [
        "aarch64_glibc_stable_2022-08-1_ld",
        "@aarch64_glibc_stable_2022-08-1//:ld",
    ],
)

filegroup(
    name = "nm",
    srcs = [
        "aarch64_glibc_stable_2022-08-1_nm",
        "@aarch64_glibc_stable_2022-08-1//:nm",
    ],
)

filegroup(
    name = "objcopy",
    srcs = [
        "aarch64_glibc_stable_2022-08-1_objcopy",
        "@aarch64_glibc_stable_2022-08-1//:objcopy",
    ],
)

filegroup(
    name = "objdump",
    srcs = [
        "aarch64_glibc_stable_2022-08-1_objdump",
        "@aarch64_glibc_stable_2022-08-1//:objdump",
    ],
)

filegroup(
    name = "strip",
    srcs = [
        "aarch64_glibc_stable_2022-08-1_strip",
        "@aarch64_glibc_stable_2022-08-1//:strip",
    ],
)

filegroup(
    name = "tool_wrappers",
    srcs = [
        ":ar",
        ":as",
        ":gcc",
        ":ld",
        ":nm",
        ":objcopy",
        ":objdump",
        ":strip",
    ],
)
