load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "python_version",
    srcs = ["python_version.py"],
    main = "python_version.py",
    # Change this to the version you want to test. See MODULE.bazel for supported versions.
    python_version = "3.13",
)
